version: "3.7"
services:
  bluesky-db:
    image: postgres
    container_name: bluesky-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgadmin"]
      interval: 5s
      timeout: 20s
      retries: 10
    volumes:
      - bluesky-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  bluesky-api:
    build: .
    container_name: bluesky-auth-server
    healthcheck:
      test: "wget -q --tries=1 --spider http://localhost:8080/docs || exit 1"
      interval: 15s
      timeout: 20s
      retries: 10
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URI=postgresql://postgres:admin@bluesky-db/postgres
      - ACCESS_TOKEN_PRIVATE_KEY=./security/private.pem
      - ACCESS_TOKEN_PUBLIC_KEY=./security/public.pem
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - REFRESH_TOKEN_EXPIRE_MINUTES=10440
      - APP_ENV=dev
    depends_on:
      - bluesky-db
  bluesky-db-migrations:
    container_name: bluesky-db-migrations
    build:
      context: .
      dockerfile: DockerfileMigrations
    environment:
      - DATABASE_URI=postgresql://postgres:admin@bluesky-db/postgres
    depends_on:
      - bluesky-db
      - bluesky-api
volumes:
  bluesky-data:
    driver: local
